// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using XIV.fm.Server.Infrastructure.Persistence;

#nullable disable

namespace XIV.fm.Server.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(XivFmDbContext))]
    [Migration("20260719101625_AddLastFmAccountLinks")]
    partial class AddLastFmAccountLinks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("XIV.fm.Server.Infrastructure.Persistence.AccountLinkSessionEntity", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset?>("AuthorizationStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("authorization_started_at");

                    b.Property<string>("CallbackStateHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("callback_state_hash")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("LinkCredentialHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("link_credential_hash")
                        .IsFixedLength();

                    b.Property<string>("ProviderTokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("provider_token_hash")
                        .IsFixedLength();

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("SessionId");

                    b.HasIndex("AccountId");

                    b.HasIndex("CallbackStateHash")
                        .IsUnique();

                    b.HasIndex("LinkCredentialHash")
                        .IsUnique();

                    b.HasIndex("ProviderTokenHash")
                        .IsUnique();

                    b.ToTable("account_link_sessions", (string)null);
                });

            modelBuilder.Entity("XIV.fm.Server.Infrastructure.Persistence.InstallationCredentialEntity", b =>
                {
                    b.Property<Guid>("InstallationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("installation_id");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CredentialHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("credential_hash")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<DateTimeOffset?>("RotatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rotated_at");

                    b.HasKey("InstallationId");

                    b.HasIndex("AccountId");

                    b.HasIndex("CredentialHash")
                        .IsUnique();

                    b.ToTable("installation_credentials", (string)null);
                });

            modelBuilder.Entity("XIV.fm.Server.Infrastructure.Persistence.LastFmAccountEntity", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("CanonicalName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("canonical_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("normalized_name");

                    b.HasKey("AccountId");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("lastfm_accounts", (string)null);
                });

            modelBuilder.Entity("XIV.fm.Server.Infrastructure.Persistence.AccountLinkSessionEntity", b =>
                {
                    b.HasOne("XIV.fm.Server.Infrastructure.Persistence.LastFmAccountEntity", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Account");
                });

            modelBuilder.Entity("XIV.fm.Server.Infrastructure.Persistence.InstallationCredentialEntity", b =>
                {
                    b.HasOne("XIV.fm.Server.Infrastructure.Persistence.LastFmAccountEntity", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Account");
                });
#pragma warning restore 612, 618
        }
    }
}
